### ISSUE TITLE
Website link (github page) is outdated

### ISSUE THREAD

**Issue by tj64** [kunstmusik/score#3]
Hi, the github page links in your readme are outdated now, just fyi: 

> 404
> There isn't a GitHub Pages site here.
> 
> Did you mean to visit [kunstmusik.github.io](https://kunstmusik.github.io/)? Please note that this site belongs to a GitHub user and  is not an official GitHub site.
 
 > If you're the owner of this site, please update your links to use kunstmusik.github.io instead. Subdomains of github.com [are   deprecated](https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/) for GitHub Pages. They will not redirect to github.io after April 15, 2021.

**Comment by kunstmusik** [comment]
Thanks for reporting!
